/**
 * Export Service
 * Export study materials as PDF or Markdown
 */

/**
 * Export notes as Markdown
 */
export const exportAsMarkdown = (topic, data) => {
    let markdown = `# ${topic}\n\n`;
    markdown += `*Generated by Study Craft AI*\n\n`;
    markdown += `---\n\n`;

    // Notes
    if (data.notes?.length) {
        markdown += `## 📝 Study Notes\n\n`;
        data.notes.forEach((note, i) => {
            markdown += `${i + 1}. ${note}\n`;
        });
        markdown += `\n`;
    }

    // Quiz
    if (data.quiz?.length) {
        markdown += `## ❓ Quiz\n\n`;
        data.quiz.forEach((q, i) => {
            markdown += `### Question ${i + 1}\n`;
            markdown += `${q.question}\n\n`;
            q.options?.forEach((opt, j) => {
                const marker = j === q.correctIndex ? '✓' : '○';
                markdown += `${marker} ${opt}\n`;
            });
            if (q.explanation) {
                markdown += `\n*Explanation: ${q.explanation}*\n`;
            }
            markdown += `\n`;
        });
    }

    // Flashcards
    if (data.flashcards?.length) {
        markdown += `## 🎴 Flashcards\n\n`;
        data.flashcards.forEach((card, i) => {
            markdown += `**Card ${i + 1}**\n`;
            markdown += `- Front: ${card.front}\n`;
            markdown += `- Back: ${card.back}\n\n`;
        });
    }

    return markdown;
};

/**
 * Download markdown as file
 */
export const downloadMarkdown = (topic, data) => {
    const markdown = exportAsMarkdown(topic, data);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `${topic.replace(/\s+/g, '_')}_study_notes.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

/**
 * Export as simple text for printing
 */
export const exportAsText = (topic, data) => {
    let text = `${topic.toUpperCase()}\n`;
    text += `${'='.repeat(topic.length)}\n\n`;

    if (data.notes?.length) {
        text += `STUDY NOTES\n-----------\n`;
        data.notes.forEach((note, i) => {
            text += `${i + 1}. ${note}\n`;
        });
        text += `\n`;
    }

    if (data.quiz?.length) {
        text += `QUIZ\n----\n`;
        data.quiz.forEach((q, i) => {
            text += `Q${i + 1}: ${q.question}\n`;
            q.options?.forEach((opt, j) => {
                text += `   ${String.fromCharCode(65 + j)}. ${opt}\n`;
            });
            text += `   Answer: ${String.fromCharCode(65 + q.correctIndex)}\n\n`;
        });
    }

    return text;
};

/**
 * Print study materials
 */
export const printMaterials = (topic, data) => {
    const content = exportAsText(topic, data);
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
        <html>
        <head>
            <title>${topic} - Study Notes</title>
            <style>
                body { font-family: 'Georgia', serif; padding: 40px; line-height: 1.6; }
                h1 { color: #333; border-bottom: 2px solid #06b6d4; }
                pre { white-space: pre-wrap; }
            </style>
        </head>
        <body>
            <h1>${topic}</h1>
            <pre>${content}</pre>
        </body>
        </html>
    `);
    printWindow.document.close();
    printWindow.print();
};

export default {
    exportAsMarkdown,
    downloadMarkdown,
    exportAsText,
    printMaterials
};
